services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=maple
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

  api-gateway:
    image: node:18-alpine
    container_name: api-gateway
    working_dir: /usr/src/app
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm run start:prod"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - AUTH_SERVICE_URL=http://auth-service:3001
      - EVENT_SERVICE_URL=http://event-service:3002

  auth-service:
    image: node:18-alpine
    container_name: auth-service
    working_dir: /usr/src/app
    volumes:
      - ./auth-service:/usr/src/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run build && npm run start:prod"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - PORT=3001

  event-service:
    image: node:18-alpine
    container_name: event-service
    working_dir: /usr/src/app
    volumes:
      - ./event-service:/usr/src/app
    ports:
      - "3002:3002"
    command: sh -c "npm install && npm run build && npm run start:prod"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - PORT=3002

volumes:
  mongodb_data: 